# This docker-compose file is meant for testing, it will not deploy the full application
version: '3'
services:
    auth-dispatcher:
        image: mrvernonliu/auth-dispatcher:0.0.1
        ports:
            - "81:80"
        networks:
            - privateNetwork
        links:
            - "auth-server"
            - "auth-webapp"

    auth-server:
        image: mrvernonliu/auth-server:0.0.2
        networks:
            - privateNetwork
        environment:
            - AUTHENTICATION_DB_USER=${AUTHENTICATION_DB_USER}
            - AUTHENTICATION_DB_PASSWORD=${AUTHENTICATION_DB_PASSWORD}
            - AUTHENTICATION_DB_NAME=${AUTHENTICATION_DB_NAME}
            - AUTHENTICATION_DB_HOST=${AUTHENTICATION_DB_HOST}
            - AUTHENTICATION_DB_PORT=${AUTHENTICATION_DB_PORT}
            - AUTHENTICATION_DB_SSL=${AUTHENTICATION_DB_SSL}
            - AUTH_SERVER_HOST=${AUTH_SERVER_HOST}
            - AUTH_WEBAPP_ORIGIN=${AUTH_WEBAPP_ORIGIN}
            - AUTH_WEBAPP_DOMAIN=${AUTH_WEBAPP_DOMAIN}

    auth-webapp:
        image: mrvernonliu/auth-webapp:0.0.3
        environment:
            - AUTH_SERVER_HOST=${AUTH_SERVER_HOST}
            - AUTH_SERVER_PORT=${AUTH_SERVER_PORT}
        networks:
            - privateNetwork

    test-client-dispatcher:
        image: mrvernonliu/test-client-dispatcher:0.0.1
        ports:
            - "82:80"
        networks:
            - privateNetwork
        links:
            - "test-client-server"
            - "test-client-webapp"
            - "auth-dispatcher"

    test-client-server:
        image: mrvernonliu/test-client-server:0.0.1
        networks:
            - privateNetwork
        links:
            - "auth-dispatcher:auth.vernonliu.com"
        environment:
            - AUTHENTICATION_DB_USER=${AUTHENTICATION_DB_USER}
            - AUTHENTICATION_DB_PASSWORD=${AUTHENTICATION_DB_PASSWORD}
            - AUTHENTICATION_DB_NAME=${AUTHENTICATION_DB_NAME}
            - AUTHENTICATION_DB_HOST=${AUTHENTICATION_DB_HOST}
            - AUTHENTICATION_DB_PORT=${AUTHENTICATION_DB_PORT}
            - AUTHENTICATION_DB_SSL=${AUTHENTICATION_DB_SSL}
            - AUTH_SERVER_HOST=${AUTH_SERVER_HOST}
            - AUTH_WEBAPP_ORIGIN=${AUTH_WEBAPP_ORIGIN}
            - AUTH_WEBAPP_DOMAIN=${AUTH_WEBAPP_DOMAIN}
            - APPLICATION_TITLE=Fake Coursespaces
            - AUTH_SERVER_LOGIN_URL=http://auth.vernonliu.com
            - AUTH_REDIRECT_URL=http://coursespaces.fakeuvic.vernonliu.com/sso
            - AUTH_CLIENT_UUID=55fba276-b6bf-4093-8f66-d93777602415
            - AUTH_CLIENT_SECRET=YfbwLJXqLnBBeuzy4bLrWw0MkGN0d8vV8YqJu-hETu4aO5EmoHsoGndLlY-A4INwOk_v7MEEtKoPeCOq0iISDA
            - AUTH_JWT_PUBLIC_KEY=-----BEGIN PUBLIC KEY-----MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEPoI3lohu4PGV064WPnozft1kdj8wNlw6lUmuegzbIm11KbwAH/cVdUa6dNR0nwgrEgeX7+AVgFz2b6L/35UlsQ==-----END PUBLIC KEY-----
            - SELF_DOMAIN_URL=http://coursespaces.fakeuvic.vernonliu.com
            - COOKIE_DOMAIN=fakeuvic.vernonliu.com

    test-client-webapp:
        image: mrvernonliu/test-client-webapp:0.0.1
        environment:
            - AUTH_SERVER_HOST=${AUTH_SERVER_HOST}
            - AUTH_SERVER_PORT=${AUTH_SERVER_PORT}
            
        networks:
            - privateNetwork
networks:
    privateNetwork: